#
# NOTE: use man zshoptions to get more info....
#

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="flazz-mv"
#ZSH_THEME="gianu"


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(colored-man-pages colorize docker git git-extras gnu-utils kubectl kube-ps1 sudo systemd rust cargo fzf)

# User configuration
# export MANPATH="/usr/local/man:$MANPATH"

#TERM
# You may need to change TERM if italic is not showed correctly.
#export TERM=xterm-256color
# Configuration when no tmux is used
[[ $TMUX = "" ]] && export TERM="xterm-256color"
# Configuration for tmux + regular vim
# export TERM=screen-256color
# Configuration for tmux + neovim
# export TERM=tmux-256color

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Do not auto-cd in a folder when typing just its name
unsetopt AUTO_CD

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
. ~/.aliases

# do not prompt from man page on openSUSE
export MAN_POSIXLY_CORRECT=
# Make colored man pages work on openSUSE
export GROFF_NO_SGR=1
# Set crictl default endpoint to crio
export CONTAINER_RUNTIME_ENDPOINT=unix:///var/run/crio/crio.sock
# Go
export GOPATH=$HOME/go

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
#export KEYTIMEOUT=1


# zsh: prompt for all completion matches even when the typed text 
# is a valid full match
zstyle ':completion:*' accept-exact false

# History
export HISTSIZE=1000000
export HISTFILESIZE=1000000
#export HISTFILE=~/.zhistory # Don't forget to to set this also

# Perl stuff
PERL5LIB="/home/marco/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/marco/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/marco/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/marco/perl5"; export PERL_MM_OPT;

# kata dev env
export KATA_DEV_MODE=true

export EDITOR=vi

export extraPath="${HOME}/bin:${GOPATH}/bin:$HOME/perl5/bin:$HOME/.cargo/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin"
export PATH="${extraPath}:$PATH"

# Rust 
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
export FZF_DEFAULT_OPTS="--reverse --bind tab:down --cycle"

# Use 'ag' for FZF + extra ignores
if command -v ag &>/dev/null; then
    aliased="$(alias ag 2>/dev/null)"
    [ -z "${aliased} " ] && aliased="ag='ag'"

    # Extract alias command line
    ag="$(sed -E "s,^.+='(.*)'$,\1," <<< ${aliased})"

    extraIgnore=
    #[ -n "$CSROOT" ] && extraIgnore="-p ~/.extraignore"
    export FZF_DEFAULT_COMMAND="$ag ${extraIgnore}"' -g  ""'
fi

