# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="af-magic"
#ZSH_THEME="aussiegeek"
ZSH_THEME="gianu"



# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(adb debian mercurial colorize colored-man-pages git ruby gnu-utils sudo python git-extras node)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/home/marco/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/jre1.6.0_31/bin


export HGEDITOR=vim

source ~/.mrvl_aliases

source ~/.my_aliases

# Add the HG advanced prompt
source ~/.promptrc


# Make TMUX display all 256 colors
export TERM=xterm-256color


#
#Support crappy arm env libs, needed on x32 only.
#
#if which armcc 2>&1 > /dev/null;
#then
#    alias vi="LD_LIBRARY_PATH=\"\" vi"
#    alias vim="LD_LIBRARY_PATH=\"\" vim"
#    alias gvim="LD_LIBRARY_PATH=\"\" gvim"
#fi


##
## Support VCXSRV HW rendering
##
#export LIBGL_ALWAYS_INDIRECT=1


# To support teraterm
#bindkey "^[[H" beginning-of-line
#bindkey "^[[1~" beginning-of-line
#bindkey "^[OH" beginning-of-line
#bindkey "^[[F"  end-of-line
#bindkey "^[[4~" end-of-line
#bindkey "^[OF" end-of-line

